extends Object
class_name Consts


const GAME_TICK_INTERVAL := 1.0
const GAME_TICKS_TO_LEVEL_TICK := 5

const ENERGY_TICKS_TO_GAIN := 3
const ENERGY_STARTING_AMOUNT := 6
const ENERGY_GAINED_AMOUNT := 4

const RAIN_ENERGY_COST := 2
const RAIN_ITERATIONS := 3
const RAIN_INTERVAL := 1.0
const RAIN_TILES_PER_ITERATION := 3
const RAIN_BORDER_DEPTH := 1

const SHRINE_ENERGY_COST := 5
const SHRINE_BORDER_DEPTH := 2

const DESERT_TILES_PER_ITERATION := 5
