extends Object
class_name Consts


const RAIN_ENERGY_COST := 2
const RAIN_ITERATIONS := 3
const RAIN_INTERVAL := 1.0
const RAIN_TILES_PER_ITERATION := 3
const RAIN_BORDER_DEPTH := 1

const SHRINE_ENERGY_COST := 5
const SHRINE_BORDER_DEPTH := 2

const GAME_TICK_INTERVAL := 3.0
const GAME_ENERGY_GAIN_INTERVAL := 6.0
const GAME_STARTING_ENERGY_AMOUNT := 5
const GAME_GAINED_ENERGY_AMOUNT := 5
